### ISSUE TITLE
Tooltips not disabling

### ISSUE THREAD

**Issue by tgoldenberg** [lookback/meteor-tooltips#10]
Hi, I am using the tooltips and am successfully changing the global Tooltips.disable from true to false. However, there is no change seen in the visibility of the actual tooltips. I assumed that the tooltips would automatically be removed on setting the .disable field, but is there something else I need to do? Thank you!

**Comment by johanbrook** [comment]
Hi there!

The `Tooltips.disable` option is to completely disable tooltips on app startup. I think what you want to do is to reactively hide any open tooltip in "real time", right? If so, just call:

``` js
Tooltips.hide();
```

Let me know if that works out.

**Comment by tgoldenberg** [comment]
Hi @johanbrook, okay, so now I understand how the disable key works, but what we are looking for is when a dropdown menu is clicked, the tooltip for that menu disappear and not reappear. However, the `hide()` functionality wouldn't do that. Is there an easy and elegant solution that you recommend?

**Comment by johanbrook** [comment]
Oh, gotcha. There's currently no support in the API for disabling it for certain elements, but the interrim solution would be to programmatically remove the `data-tooltip` attribute on the element when clicking the dropdown menu.

**Comment by tgoldenberg** [comment]
Ok, got it. Thanks!
