### ISSUE TITLE
No css

### ISSUE THREAD

**Issue by Naramsim** [lookback/meteor-tooltips#11]
Hi I've installed your package via meteor add.
However i see that it does not come with CSS compiled, nor SCSS.

I think you should explicitly say this behaviour.
Telling people to customize on their own the tooltips.

**Comment by johanbrook** [comment]
@Naramsim Hi! I actually state in the [README](https://github.com/lookback/meteor-tooltips#styling) that no styling is included. But you can check out some sample styling in here: https://github.com/lookback/meteor-tooltips/blob/master/example/_tooltip.scss
