### ISSUE TITLE
How to add element to tooltips template

### ISSUE THREAD

**Issue by NvdB31** [lookback/meteor-tooltips#18]
I'd like to add an extra div element to the tooltip template, How can I do this? If I create a tooltips template myself, Meteor throws an error saying that I cannot have multiple templates with the same name.

**Comment by johanbrook** [comment]
Hey! Did you check out https://github.com/lookback/meteor-tooltips#markup ?

**Comment by NvdB31** [comment]
Hi Johan. Adding the extra DOM element inside a html attribute doesn't seem very efficient in this case. I want the element to be part of the template. Is there a way I can add the template itself?

**Comment by NvdB31** [comment]
I ended up just cloning and modifying this package and added my own element to the template. ;-)
