### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by cyllu2** [lookback/meteor-tooltips#3]
I literally copied your code and no toolips show up. Did you forget to add some instructions?

**Comment by johanbrook** [comment]
@cyllu2 Have you checked and compared with the [example](https://github.com/lookback/meteor-tooltips/tree/master/example) repo?

**Comment by cyllu2** [comment]
Yes. I installed the package, I put {{> tooltips}} at the bottom of my template, then added data-tooltip="some text" to a few different items, none of which showed any tooltips. The only difference I see in the examples the {{#tooltip}}

**Comment by johanbrook** [comment]
Is there a tooltip element just before the `body` tag when you check your app with the Web Inspector?

Note that there is no default styling included in the package.

**Comment by cyllu2** [comment]
Before the body tag? No. But I found this:

<div class="tooltip tooltip--top hide" style="position: absolute; top: 217px; left: 951px">
		
	</div>

**Comment by johanbrook** [comment]
Yep, that's correct. Anything in the console?

**Comment by eymiha** [comment]
Im not seeing the "in" class being added to the div. Which means the opacity stays 0 and the never animates to 0.9... I haven't looked any deeper to determine why the class isn't being added.

**Comment by cyllu2** [comment]
No, nothing in the console.

**Comment by johanbrook** [comment]
It works for me in the example app, both local clone and online at tooltips.meteor.com. Are you sure you haven't missed anything?

**Comment by wizonesolutions** [comment]
I see the behavior, but maybe the CSS is incompatible with certain setups? I see text appear if I set `opacity: 1` on `tooltip.tooltip--top.show`, though it still doesn't look quite right. It's basically invisible, even though it shows in the correct spot.

**Comment by wizonesolutions** [comment]
...ah. There *is* no default CSS in the package, as explained in the README :)

so people expecting the behavior in the demo will not see it. that's probably what happened above.

**Comment by kulttuuri** [comment]
Just a FYI that I think that author really should more prominently on top of readme file mention that there is no CSS included as I also stumbled upon the same problem as "no CSS, you need to do it yourself" is hidden somewhere along the readme text. There was also only SASS example stylesheet included and no less / css, might be ideal to have those included, too.

**Comment by johanbrook** [comment]
True, thanks for reporting in.
