### ISSUE TITLE
Inner html in data-tooltip attribute

### ISSUE THREAD

**Issue by jsamr** [lookback/meteor-tooltips#4]
Hi! I'd like to be able to use inner html inside the tooltip, like this : 

```
<span data-tooltip="<em>Hi!</em>"></span>
```

Or perhaps better : 

```
<span data-tooltip-inner="true">
    <span data-tooltip-inner-html>
        <em>Hi!</em>
    </span>
</span>
```

**Comment by johanbrook** [comment]
Noted, will have a look at this.

**Comment by jsamr** [comment]
Thanks a lot, that would be a great feature :=)

**Comment by johanbrook** [comment]
@sveinburne Can you pull down `master` into your `packages` directory and try it out? I made some fixes in https://github.com/lookback/meteor-tooltips/commit/828b450f1d1b9f3c9011aa568c33e852bea8308c and https://github.com/lookback/meteor-tooltips/commit/1668076e4bce216439d531cefcefadeac54f43cc.

**Comment by jsamr** [comment]
Works great! Thanks a lot :)
