### ISSUE TITLE
Reactive blaze data not updating.

### ISSUE THREAD

**Issue by jsamr** [lookback/meteor-tooltips#5]
If I write something like : 

```
<span  data-tooltip="{{minutes}} - {{observations}}" style="left: {{leftOffset}}px;" ></span>
```

The `data-tooltip` attribute will update reactively but the the tooltip content won't. Is that the expected behaviour?

**Comment by johanbrook** [comment]
That's expected for now. I haven't figured out a nice, user friendly way of doing reactive tooltips yet, mostly due to Blaze limitations in regards to having reactive stuff in attributes. 

This is for sure needed, so I'd love to have it. PRs are welcome too.

**Comment by jsamr** [comment]
Replacing 

```
$el.data('tooltip')
```

with 

```
$el.attr('data-tooltip')
```

on line 81 does the trick! The reason is that jquery does not updates its `data-` cached objects accessible with `.data()`  when attributes change... which is a pitty... see [this SO post](http://stackoverflow.com/questions/9768165/jquery-data-selector-not-updating-with-data). I didn't offer a PR since I didn't get exactly how your `tooltip-element` worked, and it woud have been awkward to have this feature half implemented!

**Comment by johanbrook** [comment]
Fixed in `master`.
