### ISSUE TITLE
Allow different triggers

### ISSUE THREAD

**Issue by alondahari** [lookback/meteor-tooltips#6]
Bootstrap's tooltip allows for different triggers for displaying the tooltips: http://getbootstrap.com/javascript/#tooltips-options

I think it can be very useful, especially when dealing with mobile devices. In fact, I need that feature for the project I'm working on now.

I can create a pull request if you think it will be good.

Thanks!

**Comment by johanbrook** [comment]
Would be a nice addition indeed! Feel free to file a PR. I guess we'll include the events `click hover focus`.

**Comment by alondahari** [comment]
Sure. I'll see if 'manual' would be also easy enough to integrate.
