### ISSUE TITLE
IE: incorrect position in some cases

### ISSUE THREAD

**Issue by Kupuyc** [lookback/meteor-tooltips#8]
IE have problems with the positioning. Seems like IE sorting style names when set them in DOM.

[Screenshot](http://SSMaker.ru/91977dc7/)

Template helper "position" return string like "position: absolute; top: 100px; left: 100px" but in DOM styles looks like

```
left: 100px top: 100px; 
position: absolute;
```

And tooltip container displayed in incorrect place.

Fix is simple - add semicolon in helper "position" for "left" style:

``` javascript
position: function() {
  var css;
  css = getTooltip().css;
  return "position: absolute; top: " + css.top + "px; left: " + css.left + "px;";
}
```

**Comment by johanbrook** [comment]
Hi @Kupuyc!

Thanks for reporting in! Can you pull down the fix in https://github.com/lookback/meteor-tooltips/pull/9 and test again? Thanks!

**Comment by Kupuyc** [comment]
Hi.
Ty for response. I'm sorry, but there is a little problem. I'm beginner in Meteor. I know how to install package but how I can test your fix?

**Comment by johanbrook** [comment]
@Kupuyc Clone this repo into the `packages` folder in your Meteor app (create it if it doesn't exist) and checkout the `fix/ie-position` branch. Meteor will discover the local version of the package.

So:

```
# Step into your Meteor app, create `packages` if it doesn't exist. I don't know how to do that on Windows.
cd packages
git clone git@github.com:lookback/meteor-tooltips.git lookback:tooltips
git fetch origin
git checkout origin/fix/ie-position
# Run app
```

**Comment by Kupuyc** [comment]
@johanbrook, thank you for instruction.

All works fine now in IE. Thank you very much for fix.

**Comment by johanbrook** [comment]
@Kupuyc Great!
